// Script to generate complete 200-book catalog (100 English + 100 Hindi)
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const englishTitles = [
  ["Pride and Prejudice", "Jane Austen", "1813", "Romance & Satire", "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife. However little known the feelings or views of such a man may be on his first entering a neighbourhood, this truth is so well fixed in the minds of the surrounding families, that he is considered the rightful property of some one or other of their daughters."],
  ["Sense and Sensibility", "Jane Austen", "1811", "Romance & Comedy", "The family of Dashwood had long been settled in Sussex. Their estate was large, and their residence was at Norland Park, in the centre of their property, where, for many generations, they had lived in so respectable a manner as to engage the general good opinion of their surrounding acquaintance."],
  ["Emma", "Jane Austen", "1815", "Romance & Wit", "Emma Woodhouse, handsome, clever, and rich, with a comfortable home and happy disposition, seemed to unite some of the best blessings of existence; and had lived nearly twenty-one years in the world with very little to distress or vex her."],
  ["Persuasion", "Jane Austen", "1817", "Romance & Melodrama", "Sir Walter Elliot, of Kellynch Hall, in Somersetshire, was a man who, for his own amusement, never took up any book but the Baronetage; there he found occupation for an idle hour, and consolation in a distressed one; there his faculties were roused into admiration and respect, by contemplating the limited remnant of the earliest patents."],
  ["Mansfield Park", "Jane Austen", "1814", "Victorian Classic", "About thirty years ago Miss Maria Ward, of Huntingdon, with only seven thousand pounds, had the good luck to captivate Sir Thomas Bertram, of Mansfield Park, in the county of Northampton, and to be thereby raised to the rank of a baronet's lady, with all the comforts and consequences of an handsome house and large income."],
  ["Northanger Abbey", "Jane Austen", "1817", "Gothic Parody", "No one who had ever seen Catherine Morland in her infancy would have supposed her born to be an heroine. Her situation in life, the character of her father and mother, her own person and disposition, were all equally against her."],
  ["Frankenstein", "Mary Shelley", "1818", "Gothic Sci-Fi", "You will rejoice to hear that no disaster has accompanied the commencement of an enterprise which you have regarded with such evil forebodings. I arrived here yesterday, and my first task is to assure my dear sister of my welfare and increasing confidence in the success of my undertaking."],
  ["Dracula", "Bram Stoker", "1897", "Gothic Horror", "3 May. Bistritz. Left Munich at 8:35 P. M., on 1st May, arriving at Vienna early next morning; should have arrived at 6:46, but train was an hour late. Buda-Pesth seems a wonderful place, from the glimpse which I got of it from the train and the little I could see from the streets."],
  ["The Picture of Dorian Gray", "Oscar Wilde", "1890", "Philosophical Gothic", "The studio was filled with the rich odour of roses, and when the light summer wind stirred amidst the trees of the garden, there came through the open door the heavy scent of the lilac, or the more delicate perfume of the pink-flowering thorn."],
  ["The Importance of Being Earnest", "Oscar Wilde", "1895", "Satirical Comedy", "Algernon Moncrieff's flat in Half-Moon Street. The room is luxuriously and artistically furnished. The sound of a piano is heard in the adjoining room. Lane is arranging afternoon tea on the table, and after the music has ceased, Algernon enters."],
  ["The Adventures of Sherlock Holmes", "Arthur Conan Doyle", "1892", "Mystery & Detective", "To Sherlock Holmes she is always THE woman. I have seldom heard him mention her under any other name. In his eyes she eclipses and predominates the whole of her sex. It was not that he felt any emotion akin to love for Irene Adler."],
  ["The Hound of the Baskervilles", "Arthur Conan Doyle", "1902", "Gothic Mystery", "Mr. Sherlock Holmes, who was usually very late in the mornings, save upon those not infrequent occasions when he was up all night, was seated at the breakfast table. I stood upon the hearth-rug and picked up the stick which our visitor had left behind him the night before."],
  ["A Study in Scarlet", "Arthur Conan Doyle", "1887", "Detective Fiction", "In the year 1878 I took my degree of Doctor of Medicine of the University of London, and proceeded to Netley to go through the course prescribed for surgeons in the army."],
  ["The Sign of the Four", "Arthur Conan Doyle", "1890", "Detective Fiction", "Sherlock Holmes took his bottle from the corner of the mantelpiece, and his hypodermic syringe from its neat morocco case. With his long, white, nervous fingers he adjusted the delicate needle and rolled back his left shirtcuff."],
  ["The Valley of Fear", "Arthur Conan Doyle", "1915", "Detective Fiction", "I am inclined to think— said I. I should do so, Sherlock Holmes remarked impatiently. I believe that I am one of the most long-suffering of mortals; but I'll admit that I was annoyed at the sardonic interruption."],
  ["Jane Eyre", "Charlotte Brontë", "1847", "Gothic Romance", "There was no possibility of taking a walk that day. We had been wandering, indeed, in the leafless shrubbery an hour in the morning; but since dinner the cold winter wind had brought with it clouds so sombre, and a rain so penetrating, that further outdoor exercise was now out of the question."],
  ["Wuthering Heights", "Emily Brontë", "1847", "Tragedy & Romance", "1801. I have just returned from a visit to my landlord, the solitary neighbour that I shall be troubled with. This is certainly a beautiful country! In all England, I do not believe that I could have fixed on a situation so completely removed from the stir of society."],
  ["Agnes Grey", "Anne Brontë", "1847", "Victorian Classic", "All true histories contain instruction; though, in some, the treasure may be hard to find, and when found, so trivial in quantity that the dry, shrivelled kernel will scarcely compensate for the trouble of cracking the nut."],
  ["Great Expectations", "Charles Dickens", "1861", "Victorian Classic", "My father's family name being Pirrip, and my christian name Philip, my infant tongue could make of both names nothing longer or more explicit than Pip. So, I called myself Pip, and came to be called Pip."],
  ["A Tale of Two Cities", "Charles Dickens", "1859", "Historical Fiction", "It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair."],
  ["Oliver Twist", "Charles Dickens", "1838", "Social Drama", "Among other public buildings in a certain town, which for many reasons it will be prudent to refrain from mentioning, and to which I will assign no fictitious name, there is one anciently common to most towns, great or small: to wit, a workhouse."],
  ["David Copperfield", "Charles Dickens", "1850", "Bildungsroman", "Whether I shall turn out to be the hero of my own life, or whether that station will be held by anybody else, these pages must show. To begin my life with the beginning of my life, I record that I was born (as I have been informed and believe) on a Friday, at twelve o'clock at night."],
  ["A Christmas Carol", "Charles Dickens", "1843", "Holiday Classic", "Marley was dead: to begin with. There is no doubt whatever about that. The register of his burial was signed by the clergyman, the clerk, the undertaker, and the chief mourner. Scrooge signed it: and Scrooge's name was good upon 'Change, for anything he chose to put his hand to."],
  ["Bleak House", "Charles Dickens", "1853", "Legal Mystery", "London. Michaelmas term lately over, and the Lord Chancellor sitting in Lincoln's Inn Hall. Implacable November weather. As much mud in the streets as if the waters had but newly retired from the face of the earth."],
  ["Hard Times", "Charles Dickens", "1854", "Industrial Fiction", "Now, what I want is, Facts. Teach these boys and girls nothing but Facts. Facts alone are wanted in life. Plant nothing else, and root out everything else. You can only form the minds of reasoning animals upon Facts: nothing else will ever be of any service to them."],
  ["The Time Machine", "H.G. Wells", "1895", "Science Fiction", "The Time Traveller (for so it will be convenient to speak of him) was expounding a recondite matter to us. His grey eyes shone and twinkled, and his usually pale face was flushed and animated."],
  ["The War of the Worlds", "H.G. Wells", "1898", "Science Fiction", "No one would have believed in the last years of the nineteenth century that this world was being watched keenly and closely by intelligences greater than man's and yet as mortal as his own."],
  ["The Invisible Man", "H.G. Wells", "1897", "Sci-Fi Horror", "The stranger came early in February, one wintry day, through a biting wind and a driving snow, the last snowfall of the year, over the down, walking from Bramblehurst railway station, and carrying a little black portmanteau in his thickly gloved hand."],
  ["The Island of Doctor Moreau", "H.G. Wells", "1896", "Philosophical Sci-Fi", "On February the 1st, 1887, the Lady Vain was lost by collision with a derelict when about the latitude 1 deg. S. and longitude 107 deg. W. I was one of the three passengers who took to the small boat."],
  ["Twenty Thousand Leagues Under the Sea", "Jules Verne", "1870", "Submarine Sci-Fi", "The year 1866 was signalised by a remarkable incident, a mysterious and puzzling phenomenon, which doubtless no one has yet forgotten. Vessels had been met by an enormous thing, a long object, infinitely larger and more rapid than a whale."],
  ["Around the World in Eighty Days", "Jules Verne", "1872", "Globe-Trotting Adventure", "Mr. Phileas Fogg lived, in 1872, at No. 7, Saville Row, Burlington Gardens, the house in which Sheridan died in 1814. He was one of the most noticeable members of the Reform Club, though he seemed always to avoid attracting attention."],
  ["Journey to the Center of the Earth", "Jules Verne", "1864", "Sci-Fi Adventure", "On the 24th of May, 1863, my uncle, Professor Lidenbrock, rushed into his little house, No. 19 Königstrasse, one of the oldest streets in the oldest portion of the city of Hamburg."],
  ["The Mysterious Island", "Jules Verne", "1875", "Survival Adventure", "Are we rising again? No. On the contrary. Are we descending? Worse than that, captain! We are falling! For heaven's sake heave out ballast! There, the last sack is empty! Does the balloon rise? No! I hear the squalling of the sea!"],
  ["Alice’s Adventures in Wonderland", "Lewis Carroll", "1865", "Fantasy & Children", "Alice was beginning to get very tired of sitting by her sister on the bank, and of having nothing to do: once or twice she had peeped into the book her sister was reading, but it had no pictures or conversations in it."],
  ["Through the Looking-Glass", "Lewis Carroll", "1871", "Fantasy & Children", "One thing was certain, that the white kitten had had nothing to do with it: it was the black kitten's fault entirely. For the white kitten had been having its face washed by the old cat for the last quarter of an hour."],
  ["The Great Gatsby", "F. Scott Fitzgerald", "1925", "Modernist Classic", "In my younger and more vulnerable years my father gave me some advice that I have been turning over in my mind ever since. Whenever you feel like criticizing anyone, he told me, just remember that all the people in this world haven't had the advantages that you've had."],
  ["This Side of Paradise", "F. Scott Fitzgerald", "1920", "Jazz Age Bildungsroman", "Amory Blaine inherited from his mother every trait, except the stray tendencies to waver, which he derived from his father, an ineffectual, inarticulate man with a taste for Byron and a habit of reading himself to sleep on the sofa."],
  ["The Beautiful and Damned", "F. Scott Fitzgerald", "1922", "Jazz Age Tragedy", "Anthony Patch had two years before, under a system of education that was like a sieve, been given a diploma from Harvard. In 1913, when Anthony Patch was twenty-five, two years were already gone to where the centuries go."],
  ["Moby-Dick", "Herman Melville", "1851", "Adventure & Allegory", "Call me Ishmael. Some years ago, never mind how long precisely, having little or no money in my purse, and nothing particular to interest me on shore, I thought I would sail about a little and see the watery part of the world."],
  ["Bartleby, the Scrivener", "Herman Melville", "1853", "Philosophical Satire", "I am a rather elderly man. The nature of my avocations, for the last thirty years, has brought me into more than ordinary contact with what would seem an interesting and somewhat singular set of men, of whom, as yet, nothing that I know of, has ever been written."],
  ["Heart of Darkness", "Joseph Conrad", "1899", "Psychological Novella", "The Nellie, a cruising yawl, swung to her anchor without a flutter of the sails, and was at rest. The flood had made, the wind was nearly calm, and being bound down the river, the only thing for it was to come to and wait for the turn of the tide."],
  ["Lord Jim", "Joseph Conrad", "1900", "Maritime Tragedy", "He was an inch, perhaps two, under six feet, powerfully built, and he advanced straight at you with a slight stoop of the shoulders, head forward, and a fixed from-under stare which made you think of a charging bull."],
  ["The Secret Agent", "Joseph Conrad", "1907", "Espionage Drama", "Mr Verloc, going out in the morning, left his shop nominally in charge of his brother-in-law. It could be done, because there was very little business at any time, and practically none at all before the evening."],
  ["Metamorphosis", "Franz Kafka", "1915", "Absurdist Fiction", "One morning, when Gregor Samsa woke from troubled dreams, he found himself transformed in his bed into a horrible vermin. He lay on his armour-like back, and if he lifted his head a little he could see his brown belly."],
  ["The Trial", "Franz Kafka", "1925", "Existential Dystopia", "Someone must have slandered Josef K., for one morning, without having done anything truly wrong, he was arrested. Mrs. Grubach's cook, who brought him his breakfast each morning at eight, did not show up that day."],
  ["Crime and Punishment", "Fyodor Dostoevsky", "1866", "Psychological Thriller", "On an exceptionally hot evening early in July a young man came out of the garret in which he lodged in S. Place and walked slowly, as though in hesitation, towards K. bridge. He had successfully avoided meeting his landlady on the stairs."],
  ["The Brothers Karamazov", "Fyodor Dostoevsky", "1880", "Philosophical Drama", "Alexey Fyodorovich Karamazov was the third son of Fyodor Pavlovich Karamazov, a land owner well known in our district in his own day, and still remembered among us owing to his gloomy and tragic death, which happened thirteen years ago."],
  ["The Idiot", "Fyodor Dostoevsky", "1869", "Philosophical Fiction", "Towards the end of November, during a warm thaw, at around nine o'clock in the morning, a train on the Warsaw-Petersburg railway was approaching Petersburg at full speed. The morning was so damp and foggy that daylight had hardly broken."],
  ["Notes from Underground", "Fyodor Dostoevsky", "1864", "Existential Monologue", "I am a sick man... I am a spiteful man. I am an unattractive man. I believe my liver is diseased. However, I know nothing at all about my disease, and do not know for certain what ails me."],
  ["War and Peace", "Leo Tolstoy", "1869", "Historical Epic", "Well, Prince, so Genoa and Lucca are now just family estates of the Buonapartes. But I warn you, if you don't tell me that this means war, if you still try to defend the infamies and horrors perpetrated by that Antichrist, I will have nothing more to do with you!"],
  ["Anna Karenina", "Leo Tolstoy", "1877", "Tragic Romance", "All happy families are alike; each unhappy family is unhappy in its own way. Everything was in confusion in the Oblonskys' house. The wife had discovered that the husband was carrying on an intrigue with a French girl."],
  ["The Death of Ivan Ilyich", "Leo Tolstoy", "1886", "Philosophical Novella", "During an interval in the Melvinsky trial the members and the public prosecutor met in Ivan Egorovich Shebek's private room, where the conversation turned on the celebrated Krasovsky case."],
  ["Resurrection", "Leo Tolstoy", "1899", "Moral Realism", "Though men in their hundreds of thousands had tried hard to disfigure the small patch of ground on which they were crowded, paving it with stones so that nothing might grow, yet spring was spring even in the town."],
  ["The Count of Monte Cristo", "Alexandre Dumas", "1844", "Revenge Epic", "On the 24th of February, 1815, the look-out at Notre-Dame de la Garde signalled the three-master, the Pharaon, from Smyrna, Trieste, and Naples. A pilot put off immediately, and got on board the vessel between Cape Morgion and Rion island."],
  ["The Three Musketeers", "Alexandre Dumas", "1844", "Swashbuckling Adventure", "On the first Monday of the month of April, 1625, the market town of Meung, in which the author of Romance of the Rose was born, appeared to be in as perfect a state of revolution as if the Huguenots had just made a second Rochelle of it."],
  ["Twenty Years After", "Alexandre Dumas", "1845", "Historical Adventure", "In a splendid chamber of the Palais Cardinal, which we have already seen, sat a man wrapped in thought. It was Mazarin, the successor to Richelieu, surveying the troubled kingdom of France."],
  ["Les Misérables", "Victor Hugo", "1862", "Social Drama Epic", "In 1815, M. Charles-François-Bienvenu Myriel was Bishop of Digne. He was an old man of about seventy-five years of age; he had occupied the see of Digne since 1806."],
  ["The Hunchback of Notre-Dame", "Victor Hugo", "1831", "Gothic Tragedy", "Three hundred and forty-eight years, six months, and nineteen days ago to-day, the Parisians awoke to the sound of all the bells in the triple circuit of the city, the university, and the town ringing a full peal."],
  ["The Strange Case of Dr Jekyll and Mr Hyde", "Robert Louis Stevenson", "1886", "Gothic Mystery", "Mr. Utterson the lawyer was a man of a rugged countenance that was never lighted by a smile; cold, scanty and embarrassed in discourse; backward in sentiment; lean, long, dusty, dreary and yet somehow lovable."],
  ["Treasure Island", "Robert Louis Stevenson", "1883", "Pirate Adventure", "Squire Trelawney, Dr. Livesey, and the rest of these gentlemen having asked me to write down the whole particulars about Treasure Island, from the beginning to the end, keeping nothing back but the bearings of the island."],
  ["Kidnapped", "Robert Louis Stevenson", "1886", "Scottish Adventure", "I will begin the story of my adventures with a certain morning early in the month of June, the year of grace 1751, when I took the key for the last time out of the door of my father's house."],
  ["The Call of the Wild", "Jack London", "1903", "Wilderness Adventure", "Buck did not read the newspapers, or he would have known that trouble was brewing, not alone for himself, but for every tide-water dog, strong of muscle and with warm, long hair, from Puget Sound to San Diego."],
  ["White Fang", "Jack London", "1906", "Wilderness Adventure", "Dark spruce forest frowned on either side the frozen waterway. The trees had been stripped by a recent wind of their white covering of frost, and they seemed to lean towards each other, black and ominous, in the fading light."],
  ["The Sea-Wolf", "Jack London", "1904", "Maritime Adventure", "I scarcely know where to begin, though I sometimes facetiously place the cause of it all at Charley Furuseth's door. He smoked cigars and read Nietzsche in the quiet of his Mill Valley cottage."],
  ["The Scarlet Letter", "Nathaniel Hawthorne", "1850", "Historical Romance", "A throng of bearded men, in sad-coloured garments and gray, steeple-crowned hats, intermixed with women, some wearing hoods, and others bareheaded, was assembled in front of a wooden edifice."],
  ["The House of the Seven Gables", "Nathaniel Hawthorne", "1851", "Gothic Romance", "Half-way down a by-street of one of our New England towns stands a rusty wooden house, with seven acutely pointed gables, facing towards various points of the compass, and a huge, clustered chimney in the midst."],
  ["The Adventures of Tom Sawyer", "Mark Twain", "1876", "Adventure & Humor", "TOM! No answer. TOM! No answer. What's gone with that boy, I wonder? You TOM! No answer. The old lady pulled her spectacles down and looked over them about the room; then she put them up and looked out under them."],
  ["Adventures of Huckleberry Finn", "Mark Twain", "1884", "American Classic", "You don't know about me without you have read a book by the name of The Adventures of Tom Sawyer; but that ain't no matter. That book was made by Mr. Mark Twain, and he told the truth, mainly."],
  ["A Connecticut Yankee in King Arthur's Court", "Mark Twain", "1889", "Satirical Fantasy", "It was in Warwick Castle that I first met the strange stranger. What caught my eye was three things: his candid simplicity, his marvelous familiarity with ancient armor, and his unhurried modern voice."],
  ["The Prince and the Pauper", "Mark Twain", "1881", "Historical Satire", "In the ancient city of London, on a certain autumn day in the second quarter of the sixteenth century, a boy was born to a poor family of the name of Canty, who did not want him. On the same day another English child was born to a rich family of the name of Tudor, who did want him."],
  ["Ulysses", "James Joyce", "1922", "Modernist Epic", "Stately, plump Buck Mulligan came from the stairhead, bearing a bowl of lather on which a mirror and a razor lay crossed. A yellow dressinggown, ungirdled, was sustained gently behind him on the mild morning air."],
  ["Dubliners", "James Joyce", "1914", "Irish Short Stories", "There was no hope for him this time: it was the third stroke. Night after night I had passed the house and studied the lighted square of window: and night after night I had found it lighted in the same way, faintly and evenly."],
  ["A Portrait of the Artist as a Young Man", "James Joyce", "1916", "Modernist Classic", "Once upon a time and a very good time it was there was a moocow coming down along the road and this moocow that was coming down along the road met a nicens little boy named baby tuckoo."],
  ["Middlemarch", "George Eliot", "1871", "Victorian Masterpiece", "Miss Brooke had that kind of beauty which seems to be thrown into relief by poor dress. Her hand and wrist were so finely formed that she could wear sleeves not less bare of style than those in which the Blessed Virgin appeared to Italian painters."],
  ["Silas Marner", "George Eliot", "1861", "Moral Fable", "In the days when the spinning-wheels hummed busily in the farmhouses—and even great ladies, clothed in silk and thread-lace, had their toy spinning-wheels of carved oak—there might be seen in districts far away among the lanes, certain pallid undersized men."],
  ["The Mill on the Floss", "George Eliot", "1860", "Tragic Bildungsroman", "A wide plain, where the broadening Floss hurries on between its green banks to the sea, and the loving tide, rushing to meet it, checks its passage within an impetuous embrace."],
  ["Don Quixote", "Miguel de Cervantes", "1605", "Chivalric Parody", "In a village of La Mancha, the name of which I have no desire to call to mind, there lived not long since one of those gentlemen that keep a lance in the lance-rack, an old buckler, a lean hack, and a greyhound for coursing."],
  ["The Iliad", "Homer", "8th c. BC", "War Epic Poetry", "Sing, O goddess, the anger of Achilles son of Peleus, that brought countless ills upon the Achaeans. Many a brave soul did it send hurrying down to Hades, and many a hero did it yield a prey to dogs and vultures."],
  ["The Odyssey", "Homer", "8th c. BC", "Epic Poetry", "Tell me, O Muse, of that ingenious hero who travelled far and wide after he had sacked the famous citadel of Troy. Many cities did he visit, and many were the nations with whose manners and customs he was acquainted."],
  ["The Republic", "Plato", "375 BC", "Political Philosophy", "I went down yesterday to the Piraeus with Glaucon the son of Ariston, that I might offer up my prayers to the goddess; and also because I wanted to see in what manner they would celebrate the festival, which was a new thing."],
  ["Meditations", "Marcus Aurelius", "180 AD", "Stoic Philosophy", "From my grandfather Verus I learned good morals and the government of my temper. From the reputation and remembrance of my father, modesty and a manly character."],
  ["Walden", "Henry David Thoreau", "1854", "Transcendentalist Essay", "When I wrote the following pages, or rather the bulk of them, I lived alone, in the woods, a mile from any neighbor, in a house which I had built myself, on the shore of Walden Pond, in Concord, Massachusetts, and earned my living by the labor of my hands only."],
  ["Civil Disobedience", "Henry David Thoreau", "1849", "Political Philosophy", "I heartily accept the motto, 'That government is best which governs least'; and I should like to see it acted up to more rapidly and systematically. Carried out, it finally amounts to this, which also I believe— 'That government is best which governs not at all'."],
  ["The Jungle", "Upton Sinclair", "1906", "Social Realism", "It was four o'clock in the afternoon, and the kitchen was crowded with women, bustling about, laughing and gossiping. In the front room there was music, violin and accordeon, and a sound of heavy boots stamping rhythmically upon the bare wooden floor."],
  ["Peter Pan", "J.M. Barrie", "1911", "Children Fantasy", "All children, except one, grow up. They soon know that they will grow up, and the way Wendy knew was this. One day when she was two years old she was playing in a garden, and she plucked another flower and ran with it to her mother."],
  ["The Wind in the Willows", "Kenneth Grahame", "1908", "Animal Fantasy", "The Mole had been working very hard all the morning, spring-cleaning his little home. First with brooms, then with dusters; then on ladders and steps and chairs, with a brush and a pail of whitewash; till he had dust in his throat and eyes."],
  ["The Secret Garden", "Frances Hodgson Burnett", "1911", "Classic Children", "When Mary Lennox was sent to Misselthwaite Manor to live with her uncle everybody said she was the most disagreeable-looking child ever seen. It was true, too. She had a little thin face and a little thin body, thin light hair and a sour expression."],
  ["A Little Princess", "Frances Hodgson Burnett", "1905", "Classic Children", "Once on a dark winter's day, when the yellow fog hung so thick and heavy in the streets of London that the lamps were lighted and the shop windows blazed with gas as they do at night, an odd-looking little girl sat in a cab with her father."],
  ["Little Women", "Louisa May Alcott", "1868", "Family Drama", "Christmas won't be Christmas without any presents, grumbled Jo, lying on the rug. It's so dreadful to be poor! sighed Meg, looking down at her old dress. I don't think it's fair for some girls to have plenty of pretty things, and other girls nothing at all."],
  ["Little Men", "Louisa May Alcott", "1871", "Family Drama", "Plumfield was an idyllic home for boys. Mrs. Jo and her husband Professor Bhaer opened their hearts and doors to young minds eager to learn, cultivate orchards, and understand the deep duties of manhood."],
  ["The Yellow Wallpaper", "Charlotte Perkins Gilman", "1892", "Psychological Horror", "It is very seldom that mere ordinary people like John and myself secure ancestral halls for the summer. A colonial mansion, a hereditary estate, I would say a haunted house, and reach the height of romantic felicity—but that would be asking too much of fate!"],
  ["The Turn of the Screw", "Henry James", "1898", "Gothic Novella", "The story had held us, round the fire, sufficiently breathless, but except the obvious remark that it was gruesome, as on Christmas Eve in an old house a strange tale should be, I remember no comment until somebody said that it was the only case he had met in which such a visitation had fallen on a child."],
  ["Daisy Miller", "Henry James", "1878", "Novella of Manners", "At the little town of Vevey, in Switzerland, there is a particularly comfortable hotel. There are, indeed, a great many hotels; for the entertainment of tourists is the business of the place."],
  ["The Portrait of a Lady", "Henry James", "1881", "Psychological Realism", "Under certain circumstances there are few hours in life more agreeable than the hour dedicated to the ceremony known as afternoon tea. There are circumstances in which, whether you partake of the tea or not, the situation is in itself delightful."],
  ["Gulliver’s Travels", "Jonathan Swift", "1726", "Satire & Fantasy", "My father had a small estate in Nottinghamshire: I was the third of five sons. He sent me to Emanuel College in Cambridge at fourteen years old, where I resided three years, and applied myself close to my studies."],
  ["Robinson Crusoe", "Daniel Defoe", "1719", "Survival Adventure", "I was born in the year 1632, in the city of York, of a good family, though not of that country, my father being a foreigner of Bremen, who settled first at Hull: he got a good estate by merchandise, and leaving off his trade, lived afterward at York."],
  ["The Age of Innocence", "Edith Wharton", "1920", "Social Realism", "On a January evening of the early seventies, Christine Nilsson was singing in Faust at the Academy of Music in New York. Though there was already talk of the erection of a new Opera House, the conservative society of New York still gathered at the old Academy."],
  ["The House of Mirth", "Edith Wharton", "1905", "Tragic Social Realism", "Selden paused in surprise. In the afternoon rush of the Grand Central Station his eyes had been refreshed by the sight of Miss Lily Bart. It was a Monday toward the end of September, and she was striding briskly toward the tracks."],
  ["Ethan Frome", "Edith Wharton", "1911", "New England Tragedy", "I had the story, bit by bit, from various people, and, as generally happens in such cases, each time it was a different story. If you know Starkfield, Massachusetts, you know the post-office. If you know the post-office you must have seen Ethan Frome drive up to it."],
  ["The Prophet", "Kahlil Gibran", "1923", "Poetic Philosophy", "Almustafa, the chosen and the beloved, who was a dawn unto his own day, had waited twelve years in the city of Orphalese for his ship that was to return and bear him back to the isle of his birth. And in the twelfth year, on the seventh day of Ielool, the month of reaping, he climbed the hill without the city walls and looked seaward; and he beheld his ship coming with the mist."]
];

const hindiTitles = [
  // Munshi Premchand (1-30)
  ["Godan (गोदान)", "मुंशी प्रेमचंद", "1936", "उपन्यास (Novel)", "होरी महतो ने दोनों बैलों को सानी-पानी देकर अपनी पत्नी धनिया से कहा, गोबर को भेज दे, ज़रा खेत पर हो आए। मैं ज़रा रायसाहब की ड्योढ़ी पर सलाम करने जा रहा हूँ। धनिया काम में लगी थी, बोली, सवेरे-सवेरे जाने की क्या जल्दी है? होरी ने सिर हिलाकर कहा, मालिक से न मिलेंगे तो काम कैसे चलेगा?"],
  ["Gaban (गबन)", "मुंशी प्रेमचंद", "1931", "उपन्यास (Novel)", "बाबू दयानाथ बड़े ही धर्मात्मा और संतोषी जीव थे। कचहरी में क्लर्क थे, पर उनकी ईमानदारी की शहर भर में धाक थी। उनका पुत्र रमानाथ शौकीन, चंचल और दिखावे का प्रेमी था। पिता की सीधी-सादी जिंदगी उसे तंग नजर आती थी। रमानाथ का विवाह जालपा से हुआ, जिसे बचपन से ही आभूषणों का असीम मोह था।"],
  ["Sevasadan (सेवासदन)", "मुंशी प्रेमचंद", "1919", "उपन्यास (Novel)", "दारोगा कृष्णचंद्र अपनी लाडली कन्या सुमन को बहुत चाहते थे। वे चाहते थे कि उसका विवाह किसी बड़े और धनवान घराने में हो। इसी लालसा में वे रिश्वतखोरी के जाल में फँस गए और अंततः जेल भेज दिए गए। पिता के जेल जाने के बाद सुमन का विवाह गरीब मुंशी गजाधर से कर दिया गया।"],
  ["Karmabhoomi (कर्मभूमि)", "मुंशी प्रेमचंद", "1932", "उपन्यास (Novel)", "लाला समरकांत काशी के प्रतिष्ठित महाजन थे। उनका व्यवसाय खूब फलता-फूलता था। उनका पुत्र अमरकांत शांत, विचारशील और समाजसेवा का प्रेमी था। पिता की धनलोलुपता और कठोरता उसे सदैव कचोटती रहती थी। अमरकांत निर्धन और उपेक्षित वर्ग के दुख-दर्द को बाँटने में सार्थकता समझता था।"],
  ["Rangbhoomi (रंगभूमि)", "मुंशी प्रेमचंद", "1924", "उपन्यास (Novel)", "पांडेपुर बनारस के समीप एक छोटा-सा गाँव था। सूरदास उसी गाँव का एक अंधा भिखारी था, पर गाँव भर में उसका आदर था। उसकी पुश्तैनी जमीन गाँव के बाहर सड़क के किनारे थी। जहाँ गाँव के ढोर चरते थे। जॉन सेवक नाम का एक व्यापारी उस जमीन पर सिगरेट का कारखाना खोलना चाहता था।"],
  ["Nirmala (निर्मला)", "मुंशी प्रेमचंद", "1927", "उपन्यास (Novel)", "उदयभानु लाल अपने घर के मालिक थे। उनके विचार पुराने थे, पर उनका हृदय कोमल था। उनकी बड़ी कन्या निर्मला अभी पंद्रह वर्ष की थी। रूप और शील दोनों में वह अपनी सहेलियों में सिरमौर थी। निर्मला का विवाह एक कुलीन घराने में तय हुआ था, किंतु विधाता को कुछ और ही मंजूर था।"],
  ["Pratigya (प्रतिज्ञा)", "मुंशी प्रेमचंद", "1929", "उपन्यास (Novel)", "अमृतराय शहर के जाने-माने वकील और सुधारक थे। उनका हृदय समाज की रूढ़ियों और कुरीतियों को देखकर विचलित हो उठता था। जब उनके मित्र की युवा विधवा पूर्णा पर समाज के अत्याचार होने लगे, तो अमृतराय ने अपने वैभवशाली जीवन को त्यागकर वनिता आश्रम स्थापित करने की अटल प्रतिज्ञा की।"],
  ["Kayakalp (कायाकल्प)", "मुंशी प्रेमचंद", "1926", "उपन्यास (Novel)", "राजा विशालसिंह जगदीशपुर रियासत के स्वामी थे, पर उनकी वृद्धावस्था और संतानहीनता उन्हें सदैव बेचैन रखती थी। चक्रधर नाम का एक तेजस्वी युवक जनता के अधिकारों की रक्षा के लिए राजदरबार के सामने डटकर खड़ा हो गया। इस महागाथा में प्रेम, राजनीति और आत्मिक कायाकल्प का अद्भुत संगम है।"],
  ["Premashram (प्रेमाश्रम)", "मुंशी प्रेमचंद", "1922", "उपन्यास (Novel)", "लखनपुर गाँव के किसान जमींदार के अत्याचारों से त्रस्त थे। प्रभातफेरी और चौपाल में किसान अपने अधिकारों की चर्चा करने लगे। प्रेमशंकर नाम के आदर्शवादी जमींदार ने किसानों के कल्याण के लिए प्रेमाश्रम की स्थापना की और शोषणमुक्त समाज की नींव रखी।"],
  ["Vardaan (वरदान)", "मुंशी प्रेमचंद", "1921", "उपन्यास (Novel)", "प्रतापनारायण का जन्म एक धार्मिक परिवार में हुआ था। उनकी माता सुवामा देवी ने भगवान विश्वनाथ से वरदान माँगा था कि उनका पुत्र देशभक्त और त्यागी बने। प्रतापनारायण ने मातृभूमि की सेवा में अपना सर्वस्व न्योछावर कर दिया।"],
  ["Mansarovar Bhag 1 (मानसरोवर भाग १)", "मुंशी प्रेमचंद", "1936", "कहानी संग्रह (Stories)", "हमारे अंग्रेजी के मास्टर साहब का नाम था मौलवी बशीरुद्दीन। वे बड़े ही नेक और मिलनसार आदमी थे। गुल्ली डंडा हमारे लड़कपन का सबसे प्रिय खेल था। न किसी लॉन की ज़रूरत, न बैट की, न गेंद की। बस एक पेड़ से टहनी काटी, गिल्ली बनाई और दोनों तरफ से नोक तराश ली।"],
  ["Mansarovar Bhag 2 (मानसरोवर भाग २)", "मुंशी प्रेमचंद", "1936", "कहानी संग्रह (Stories)", "जोखू ने लोटा मुँह से लगाया, तो पानी में सख्त बदबू आई। गंगी से बोला, यह कैसा पानी है? मारे बास के पिया नहीं जाता। गला सूखा जा रहा है और तू सड़ा पानी पिलाए देती है! गंगी प्रतिदिन शाम को पानी भर लाती थी। ठाकुर के कुएँ पर कौन पानी भरने देगा!"],
  ["Mansarovar Bhag 3 (मानसरोवर भाग ३)", "मुंशी प्रेमचंद", "1937", "कहानी संग्रह (Stories)", "मेरे भाई साहब मुझसे पाँच साल बड़े थे, लेकिन केवल तीन दरजे आगे। उन्होंने भी उसी उम्र में पढ़ना शुरू किया था जब मैंने शुरू किया था; लेकिन तालीम जैसे महत्व के मामले में वे जल्दबाजी से काम लेना पसंद न करते थे। इस भवन की बुनियाद खूब मजबूत डालना चाहते थे।"],
  ["Mansarovar Bhag 4 (मानसरोवर भाग ४)", "मुंशी प्रेमचंद", "1938", "कहानी संग्रह (Stories)", "लाला दाऊदयाल पुराने जमाने के सज्जन और धर्मात्मा पुरुष थे। शहर में उनकी कपड़े की बहुत बड़ी आढ़त थी। वे किसी गरीब का हक नहीं मारते थे। रहमान नाम का एक किसान जब अपनी गाय बेचने आया, तो लाला जी ने बिना ब्याज के पूरे दाम उसे उधार दे दिए।"],
  ["Mansarovar Bhag 5 (मानसरोवर भाग ५)", "मुंशी प्रेमचंद", "1939", "कहानी संग्रह (Stories)", "बुंदेलखंड की वीर भूमि अपने पराक्रम, स्वाभिमान और त्याग के लिए इतिहास में प्रसिद्ध है। जब ओरछा राज्य पर मुगलों की विशाल सेना ने घेरा डाला, तो रानी सारंधा ने अपने पति चंपतराय की ढाल बनकर युद्धक्षेत्र में तलवार उठाई।"],
  ["Mansarovar Bhag 6 (मानसरोवर भाग ६)", "मुंशी प्रेमचंद", "1940", "कहानी संग्रह (Stories)", "जब रियासत देवगढ़ के दीवान सरदार सुजान सिंह बूढ़े हुए, तो परमात्मा की याद आई। उन्होंने महाराज से नम्र निवेदन किया कि अब मेरी वृद्धावस्था आ गई है, अतः मुझे दीवानी के भारी भार से मुक्त किया जाए। महाराज ने सुयोग्य दीवान खोजने का भार उन्हीं पर छोड़ दिया।"],
  ["Mansarovar Bhag 7 (मानसरोवर भाग ७)", "मुंशी प्रेमचंद", "1941", "कहानी संग्रह (Stories)", "गोपीनाथ शहर के एक बहुत बड़े बैंक में खजांची थे। उनका जीवन नियमित, शांत और संयमित था। एक दिन अचानक खबर फैली कि बैंक का दिवाला निकलने वाला है। गोपीनाथ ने अपनी ईमानदारी और धैर्य से जनता के विश्वास को टूटने नहीं दिया।"],
  ["Mansarovar Bhag 8 (मानसरोवर भाग ८)", "मुंशी प्रेमचंद", "1942", "कहानी संग्रह (Stories)", "होली का त्योहार था और चारों तरफ अबीर-गुलाल उड़ रहा था। गाँव के बाल-वृद्ध सभी उल्लास में मग्न थे। गरीब किसान रामू के घर में एक मुट्ठी अनाज भी न था। तभी गाँव के पुराने मुखिया ने आकर रामू के घर मिठाइयाँ और अनाज की बोरी पहुँचाई।"],
  ["Kafan (कफ़न)", "मुंशी प्रेमचंद", "1936", "कहानी (Short Story)", "झोंपड़े के द्वार पर बाप और बेटा दोनों एक बुझे हुए अलाव के सामने चुपचाप बैठे हुए थे और अंदर बेटे की जवान बीवी बुधिया प्रसव-वेदना से पछाड़ खा रही थी। जाड़ों की रात थी, प्रकृति सन्नाटे में डूबी हुई, सारा गाँव अंधकार में लय हो गया था।"],
  ["Panch Parmeshwar (पंच परमेश्वर)", "मुंशी प्रेमचंद", "1916", "कहानी (Short Story)", "जुम्मन शेख और अलगू चौधरी में गाढ़ी मित्रता थी। साझे में खेती होती थी। कुछ लेन-देन में भी साझा था। एक को दूसरे पर अटल विश्वास था। जुम्मन जब हज करने गए थे, तब अपना घर अलगू को सौंप गए थे; और अलगू बाहर जाते, तो जुम्मन पर घर छोड़ देते थे।"],
  ["Namak Ka Daroga (नमक का दारोगा)", "मुंशी प्रेमचंद", "1925", "कहानी (Short Story)", "जब नमक का नया विभाग बना और ईश्वरप्रदत्त वस्तु के व्यवहार करने का निषेध हो गया, तो लोग चोरी-छिपे इसका व्यापार करने लगे। मुंशी वंशीधर को नमक चौकी का दारोगा बनाया गया। उन्होंने पंडित अलोपीदीन की नमक से लदी गाड़ियाँ पकड़ लीं।"],
  ["Poos Ki Raat (पूस की रात)", "मुंशी प्रेमचंद", "1930", "कहानी (Short Story)", "हल्कू ने आकर अपनी स्त्री से कहा, सहना आया है, लाओ, जो रुपये रखे हैं, उसे दे दूँ, किसी तरह गला तो छूटे। मुन्नी बोली, तीन ही तो रुपये हैं, दे दोगे तो कम्बल कहाँ से आवेगा? माघ-पूस की रात हार में कैसे कटेगी?"],
  ["Idgah (ईदगाह)", "मुंशी प्रेमचंद", "1933", "कहानी (Short Story)", "रमज़ान के पूरे तीस रोज़ों के बाद आज ईद आई है। कितना मनोहर, कितना सुहावना प्रभाव है! सबसे ज्यादा प्रसन्न है हामिद। वह चार-पाँच साल का गरीब-सूरत, दुबला-पतला लड़का, जिसके पास मेले के लिए केवल तीन पैसे थे। उसने मेले में चिमटा खरीदा।"],
  ["Do Bailon Ki Katha (दो बैलों की कथा)", "मुंशी प्रेमचंद", "1931", "कहानी (Short Story)", "जानवरों में गधा सबसे ज्यादा बुद्धिहीन समझा जाता है। जब हम किसी आदमी को पछाड़ का बेवकूफ कहना चाहते हैं, तो उसे गधा कहते हैं। झूरी काछी के दो बैल थे—हीरा और मोती। दोनों पछाईं जाति के थे, देखने में सुंदर, काम में चौकस, डील में ऊँचे।"],
  ["Bade Ghar Ki Beti (बड़े घर की बेटी)", "मुंशी प्रेमचंद", "1910", "कहानी (Short Story)", "बेनीमाधव सिंह गौरीपुर गाँव के जमींदार और नंबरदार थे। उनके दो पुत्र थे, बड़े का नाम श्रीकंठ सिंह था और छोटे का नाम लालबिहारी सिंह। श्रीकंठ का विवाह आनंदी से हुआ था। आनंदी के बड़प्पन से टूटने की कगार पर पहुँचा परिवार एक हो गया।"],
  ["Shatranj Ke Khilari (शतरंज के खिलाड़ी)", "मुंशी प्रेमचंद", "1924", "कहानी (Short Story)", "वाजिद अली शाह का समय था। लखनऊ विलासिता के रंग में डूबा हुआ था। मिर्ज़ा सज्जाद अली और मीर रौशन अली अपनी-अपनी जागीरें संभाले हुए थे। उनका मुख्य कार्य था दिन-रात आमने-सामने बैठकर शतरंज खेलना।"],
  ["Sadgati (सद्गति)", "मुंशी प्रेमचंद", "1930", "कहानी (Short Story)", "दुखी चमार द्वार पर झाड़ू लगा रहा था और उसकी पत्नी झुरिया खाट के पाए से बैठी घास छील रही थी। आज पंडित घासीराम को घर बुलाना था बेटी की सगाई का साइत विचारने के लिए। दुखी पंडित जी के घर बेगारी करने पहुँचा।"],
  ["Budhi Kaki (बूढ़ी काकी)", "मुंशी प्रेमचंद", "1921", "कहानी (Short Story)", "बुढ़ापा बहुधा बचपन का पुनरागमन हुआ करता है। बूढ़ी काकी में जीभ के स्वाद के सिवा न कोई चेष्टा शेष थी और न अपने कष्टों की ओर आकर्षित करने का रोने के अतिरिक्त कोई दूसरा सहारा ही। भतीजे बुद्धिराम के घर उत्सव में काकी पत्तलें चाटने पर विवश हुईं।"],
  ["Doodh Ka Daam (दूध का दाम)", "मुंशी प्रेमचंद", "1934", "कहानी (Short Story)", "बाबू महेशनाथ के घर में जब पुत्र पैदा हुआ, तो उत्सव मनाया गया। दाई भुंगी ने बच्चे को अपना दूध पिलाकर पाला। जब भुंगी का अपना बच्चा मंगल बड़ा हुआ, तो समाज ने उसे जूठन और अपमान के सिवा कुछ न दिया।"],
  ["Thakur Ka Kuan (ठाकुर का कुआँ)", "मुंशी प्रेमचंद", "1932", "कहानी (Short Story)", "जोखू बीमार था और प्यास से तड़प रहा था। घर में सड़ा पानी था। गंगी ने घड़ा उठाया और रात के अंधेरे में ठाकुर के कुएँ से मीठा पानी लाने निकल पड़ी। समाज के जातिवादी पहरेदारों ने उस पर दया नहीं दिखाई।"],
  // Devaki Nandan Khatri (31-44)
  ["Chandrakanta (चंद्रकांता)", "देवकीनंदन खत्री", "1888", "तिलिस्म एवं ऐयारी", "यह बात तो सब कोई जानते हैं कि नौगढ़ और विजयगढ़ दोनों पड़ोसी राज्य हैं। राजा सुरेंद्र सिंह के पुत्र वीरेंद्र सिंह और राजा जयसिंह की रूपवती कन्या चंद्रकांता में अनन्य प्रेम था। क्रूरसिंह के षड्यंत्रों के बीच ऐयार तेजसिंह ने तिलिस्म को भेदा।"],
  ["Chandrakanta Santati - Bhag 1 (चंद्रकांता संतति - भाग १)", "देवकीनंदन खत्री", "1896", "तिलिस्म एवं ऐयारी", "कुंवर वीरेंद्र सिंह और चंद्रकांता के विवाह के पश्चात उनके पुत्रों इंद्रजीत सिंह और आनंद सिंह का जन्म हुआ। रोहतासगढ़ के तिलिस्म में दोनों राजकुमारों के अद्वितीय पराक्रम की रोमांचक शुरुआत हुई।"],
  ["Chandrakanta Santati - Bhag 2 (चंद्रकांता संतति - भाग २)", "देवकीनंदन खत्री", "1897", "तिलिस्म एवं ऐयारी", "तिलिस्मी सुरंगों में फँसे राजकुमारों को बचाने के लिए ऐयार तेजसिंह, देवीसिंह और तारा ने अपने ऐयारी बटुओं से अद्भुत चमत्कार दिखाए। तिलिस्मी खंजरों और नक्शों की खोज आगे बढ़ी।"],
  ["Chandrakanta Santati - Bhag 3 (चंद्रकांता संतति - भाग ३)", "देवकीनंदन खत्री", "1898", "तिलिस्म एवं ऐयारी", "कमलिनी और लाडली की रहस्यमयी गुफा में प्रवेश हुआ। तिलिस्मी दीवानों पर लिखे गुप्त अक्षरों को पढ़कर राजकुमारों ने जादुई दरवाजों के तालों को खोला।"],
  ["Chandrakanta Santati - Bhag 4 (चंद्रकांता संतति - भाग ४)", "देवकीनंदन खत्री", "1899", "तिलिस्म एवं ऐयारी", "मायारानी के कुचक्रों और तिलिस्मी सेनापति के हमलों का सामना करते हुए वीरों ने अद्भुत धीरज दिखाया। चुनारगढ़ के खंडहरों में दबे अपार खजाने का रहस्य खुला।"],
  ["Chandrakanta Santati - Bhag 5 (चंद्रकांता संतति - भाग ५)", "देवकीनंदन खत्री", "1900", "तिलिस्म एवं ऐयारी", "तिलिस्म के मुख्य मंडप में स्थापित धातु की पुतलियों ने खड्ग घुमाकर रास्ता रोका। बुद्धिबल और ऐयारी विद्या के बल पर राजकुमारों ने पुतलियों के तंत्र को निष्क्रिय किया।"],
  ["Chandrakanta Santati - Bhag 6 (चंद्रकांता संतति - भाग ६)", "देवकीनंदन खत्री", "1905", "तिलिस्म एवं ऐयारी", "तिलिस्म के अंतिम द्वार पर पहुँचकर सभी रहस्यमयी पहेलियों का समाधान हुआ। धर्म और पराक्रम की विजय हुई और चारों दिशाओं में शांति स्थापित हुई।"],
  ["Bhootnath - Bhag 1 (भूतनाथ - भाग १)", "देवकीनंदन खत्री", "1906", "रहस्य एवं जासूसी", "आधी रात का समय था। चारों तरफ घना अंधकार छाया हुआ था। ऐसे भयानक समय में एक लंबा-चौड़ा आदमी काले रंग का लबादा ओढ़े और चेहरे पर भयानक नकाब लगाए पुराने खंडहर की ओर बढ़ा चला जा रहा था।"],
  ["Bhootnath - Bhag 2 (भूतनाथ - भाग २)", "देवकीनंदन खत्री", "1907", "रहस्य एवं जासूसी", "भूतनाथ के रहस्यमयी अतीत की परतें खुलने लगीं। गदाधर सिंह के जीवन के पुराने पश्चाताप और उसके गुप्त ठिकानों की पड़ताल ने राजा के गुप्तचरों को चकित कर दिया।"],
  ["Bhootnath - Bhag 3 (भूतनाथ - भाग ३)", "देवकीनंदन खत्री", "1908", "रहस्य एवं जासूसी", "कालकोठरियों और गुप्त सुरंगों के बीच भूतनाथ ने अपनी ऐयारी का चरम प्रदर्शन किया। अन्याय के विरुद्ध खड़े होकर उसने निर्दोषों की रक्षा का संकल्प निभाया।"],
  ["Kajar Ki Kothari (कजर की कोठरी)", "देवकीनंदन खत्री", "1902", "रहस्य उपन्यास", "संसार एक कजर की कोठरी के समान है, जहाँ कदम-कदम पर लांछन और कालिख लगने का भय रहता है। इस तिलिस्मी उपन्यास में निष्कलंक चरित्र की विजय का आख्यान है।"],
  ["Narendra Mohini (नरेन्द्र मोहिनी)", "देवकीनंदन खत्री", "1893", "रोमांचक उपन्यास", "राजकुमार नरेंद्र सिंह और मोहिनी के प्रेम, वियोग और संकटों से पार पाने के लिए ऐयारों की अद्भुत युक्तियों का जीवंत चित्रण।"],
  ["Kusum Kumari (कुसुम कुमारी)", "देवकीनंदन खत्री", "1899", "ऐतिहासिक रोमांस", "कुसुम कुमारी की बुद्धिमत्ता, वीरता और नारी सुलभ मर्यादा ने कठिन से कठिन परिस्थितियों में भी विजय की पताका फहराई।"],
  ["Virendra Veer (वीरेन्द्र वीर)", "देवकीनंदन खत्री", "1895", "वीरगाथा उपन्यास", "वीरेन्द्र वीर के अदम्य साहस, तलवारबाजी और राजभक्ति की गाथा, जिसमें छल-कपट पर सत्य और शौर्य की अमर जीत दिखाई गई है।"],
  // Jaishankar Prasad (45-61)
  ["Kamayani (कामायनी)", "जयशंकर प्रसाद", "1936", "छायावादी महाकाव्य", "हिमगिरि के उत्तुंग शिखर पर, बैठ शिला की शीतल छाँह, एक पुरुष, भीगे नयनों से देख रहा था प्रलय-प्रवाह। नीचे जल था ऊपर हिम था, एक तरल था एक सघन, एक तत्त्व की ही प्रधानता, कहो उसे जड़ या चेतन।"],
  ["Skandagupta (स्कंदगुप्त)", "जयशंकर प्रसाद", "1928", "ऐतिहासिक नाटक", "अधिकार-सुख कितना मादक और सारहीन है! अपने को नियामक और कर्त्ता समझने की बलवती स्पृहा उससे बेगार कराती है। गुप्त साम्राज्य की रक्षा के लिए स्कंदगुप्त ने हूणों को परास्त किया।"],
  ["Chandragupta (चंद्रगुप्त)", "जयशंकर प्रसाद", "1931", "ऐतिहासिक नाटक", "अरुण यह मधुमय देश हमारा! जहाँ पहुँच अनजान क्षितिज को मिलता एक सहारा। चाणक्य की कूटनीति और चंद्रगुप्त के पराक्रम से अखंड भारत का निर्माण हुआ।"],
  ["Dhruvaswamini (ध्रुवस्वामिनी)", "जयशंकर प्रसाद", "1933", "नारी-चेतना नाटक", "क्लीव, कायर रामगुप्त के चंगुल से नारी के आत्मसम्मान की रक्षा के लिए ध्रुवस्वामिनी और चंद्रगुप्त का साहसिक विद्रोह।"],
  ["Ajatashatru (अजातशत्रु)", "जयशंकर प्रसाद", "1922", "ऐतिहासिक नाटक", "मगध, कौशांबी और श्रावस्ती के त्रिकोणीय संघर्ष में तथागत बुद्ध की करुणा और शांति का अमर संदेश।"],
  ["Janamejaya Ka Nagyajna (जनमेजय का नागयज्ञ)", "जयशंकर प्रसाद", "1926", "पौराणिक नाटक", "तक्षक नाग और राजा जनमेजय के प्रतिशोध के बीच आस्तीक मुनि द्वारा हिंसा के निवारण और विश्व-बंधुत्व की स्थापना।"],
  ["Titli (तितली)", "जयशंकर प्रसाद", "1934", "सामाजिक उपन्यास", "ग्रामीण जीवन के यथार्थ, जमींदारों के शोषण और तितली के स्वावलंबन व आत्मबल की प्रेरक सामाजिक कथा।"],
  ["Kankal (कंकाल)", "जयशंकर प्रसाद", "1929", "यथार्थवादी उपन्यास", "धार्मिक पाखंड, समाज के सड़े-गले बंधनों और कंकाल बने इंसानों के आत्मिक विद्रोह का नग्न यथार्थ।"],
  ["Iravati (इरावती)", "जयशंकर प्रसाद", "1936", "ऐतिहासिक उपन्यास", "शुंग वंश के संस्थापक पुष्यमित्र शुंग के कालखंड की पृष्ठभूमि पर रचित प्रसाद जी का अंतिम अपूर्ण ऐतिहासिक उपन्यास।"],
  ["Aakashdeep (आकाशदीप)", "जयशंकर प्रसाद", "1928", "कहानी संग्रह (Stories)", "बंदी! क्या है? सोने दो। मुक्त होना चाहते हो? अभी नहीं। चंपा और बुद्धगुप्त का समुद्र के द्वीप पर प्रेम और कर्तव्य का अमर द्वंद्व।"],
  ["Aandhi (आंधी)", "जयशंकर प्रसाद", "1931", "कहानी संग्रह (Stories)", "जीवन की आंधियों में बिखरते सपनों और कर्तव्य की वेदी पर प्रेम के मूक समर्पण की भावुक कहानियाँ।"],
  ["Pratidhvani (प्रतिध्वनि)", "जयशंकर प्रसाद", "1926", "कहानी संग्रह (Stories)", "प्रसाद जी की दार्शनिक और मनोवैज्ञानिक कहानियों का संग्रह, जहाँ अंतर्मन की प्रतिध्वनि गूँजती है।"],
  ["Chhaya (छाया)", "जयशंकर प्रसाद", "1912", "कहानी संग्रह (Stories)", "प्रसाद जी का प्रथम कहानी संग्रह, जिसमें भारतीय संस्कृति, करुणा और मानवीय संवेदनाओं का अंकन है।"],
  ["Indrajaal (इंद्रजाल)", "जयशंकर प्रसाद", "1936", "कहानी संग्रह (Stories)", "संसार के मायावी इंद्रजाल में उलझे मानव जीवन के रहस्य और विडंबनाओं का यथार्थवादी चित्रण।"],
  ["Ansoo (आँसू)", "जयशंकर प्रसाद", "1925", "स्मृति काव्य (Poetry)", "इस करुणा कलित हृदय में अब विकल रागिनी बजती, क्यों हाहाकार स्वरों में वेदना असीम गरजती? विरह की ज्वाला से तपे मन की अमर काव्य-रचना।"],
  ["Jharna (झरना)", "जयशंकर प्रसाद", "1918", "छायावादी काव्य (Poetry)", "छायावाद की प्रयोगशाला कहा जाने वाला काव्य-संग्रह, जिसमें प्रकृति और सौंदर्य के मधुर निर्झर बहते हैं।"],
  ["Lahar (लहर)", "जयशंकर प्रसाद", "1933", "प्रगीत काव्य (Poetry)", "बीती विभावरी जाग री! अंबर पनघट में डुबो रही तारा घट ऊषा नागरी। नवजागरण और चेतना का शंखनाद।"],
  // Bharatendu Harishchandra (62-69)
  ["Andher Nagari (अंधेर नगरी)", "भारतेन्दु हरिश्चन्द्र", "1881", "प्रहसन नाटक (Satire)", "अंधेर नगरी अनबूझ राजा, टके सेर भाजी टके सेर खाजा। महंत जी और गोवर्धन दास का न्यायविहीन सत्ता पर अमर व्यंग्य नाटक।"],
  ["Bharat Durdasha (भारत दुर्दशा)", "भारतेन्दु हरिश्चन्द्र", "1880", "राष्ट्रीय नाटक", "रोअहु सब मिलिकै आवहु भारत भाई, हा हा! भारत-दुर्दशा न देखी जाई। भारतेंदु जी का राष्ट्रीय चेतना जगाने वाला अमर नाटक।"],
  ["Satya Harishchandra (सत्य हरिश्चंद्र)", "भारतेन्दु हरिश्चन्द्र", "1875", "पौराणिक नाटक", "चंद्र टरै सूरज टरै, टरै जगत व्यवहार, पै दृढ़ श्रीहरिश्चंद्र को, टरै न सत्य विचार। राजा हरिश्चंद्र की सत्यनिष्ठा का पावन आख्यान।"],
  ["Vaidiki Himsa Himsa Na Bhavati (वैदिकी हिंसा हिंसा न भवति)", "भारतेन्दु हरिश्चन्द्र", "1873", "सामाजिक प्रहसन", "धार्मिक पाखंड, बलि प्रथा और मांसाहार पर तीखा कटाक्ष करने वाला व्यंग्य प्रधान प्रहसन।"],
  ["Chandravali (चंद्रावली)", "भारतेन्दु हरिश्चन्द्र", "1876", "नाटिका (Drama)", "भगवान श्रीकृष्ण के प्रति गोपियों के अनन्य प्रेम और विशुद्ध भक्ति का रसमय चित्रण।"],
  ["Nil Devi (नील देवी)", "भारतेन्दु हरिश्चन्द्र", "1881", "ऐतिहासिक नाटक", "राजपूत वीरांगना नीलदेवी के शौर्य, स्वाभिमान और पति के सम्मान की रक्षा हेतु बलिदान का नाटक।"],
  ["Prem Yogini (प्रेम जोगिनी)", "भारतेन्दु हरिश्चन्द्र", "1875", "सामाजिक नाटक", "काशी के तत्कालीन धार्मिक पाखंडियों और तीर्थ पुरोहितों के अनाचारों का पर्दाफाश।"],
  ["Karpur Manjari (कर्पूर मंजरी)", "भारतेन्दु हरिश्चन्द्र", "1875", "संस्कृत अनुवाद नाटक", "महाकवि राजशेखर की प्राकृत नाटिका का भारतेंदु जी द्वारा किया गया ललित हिंदी अनुवाद।"],
  // Acharya Ramchandra Shukla & Mahavir Prasad Dwivedi (70-76)
  ["Chintamani Bhag 1 (चिंतामणि भाग १)", "आचार्य रामचंद्र शुक्ल", "1939", "मनोवैज्ञानिक निबंध", "उत्साह, करुणा, क्रोध, श्रद्धा-भक्ति, लज्जा और ग्लानि, लोभ और प्रीति—मानव मनोविकारों की अद्भुत मीमांसा।"],
  ["Chintamani Bhag 2 (चिंतामणि भाग २)", "आचार्य रामचंद्र शुक्ल", "1945", "साहित्यिक निबंध", "काव्य में प्राकृतिक दृश्य, काव्य में रहस्यवाद और काव्य में लोकमंगल की साधनावस्था के अमर वैचारिक निबंध।"],
  ["Hindi Sahitya Ka Itihas (हिंदी साहित्य का इतिहास)", "आचार्य रामचंद्र शुक्ल", "1929", "साहित्येतिहास", "हिंदी साहित्य के कालविभाजन (आदिकाल, भक्तिकाल, रीतिकाल, आधुनिक काल) का सर्वमान्य और प्रामाणिक इतिहास ग्रंथ।"],
  ["Rasa Mimamsa (रस मीमांसा)", "आचार्य रामचंद्र शुक्ल", "1949", "काव्यशास्त्र", "भारतीय रस सिद्धांत की वैज्ञानिक, मनोवैज्ञानिक और लोकमंगलकारी पुनर्व्याख्या।"],
  ["Sampatti Shastra (संपत्ति शास्त्र)", "महावीर प्रसाद द्विवेदी", "1908", "अर्थशास्त्र ग्रंथ", "भारत के आर्थिक दोहन और संपत्ति के विज्ञान पर सरल हिंदी में लिखा गया प्रथम प्रामाणिक ग्रंथ।"],
  ["Kavita Kalap (कविता कलाप)", "महावीर प्रसाद द्विवेदी", "1909", "काव्य संकलन", "द्विवेदी युगीन इतिवृत्तात्मक और नैतिकतावादी काव्यधारा का प्रतिनिधि संकलन।"],
  ["Sahitya Sikar (साहित्य सीकर)", "महावीर प्रसाद द्विवेदी", "1911", "साहित्यिक निबंध", "साहित्यिक अनुशासन, भाषा परिष्कार और ज्ञान के विविध अनुशासनों पर विचारोत्तेजक लेख।"],
  // Kishori Lal Goswami & Early Fiction (77-85)
  ["Tarun Tapaswini (तरुण तपस्विनी)", "किशोरी लाल गोस्वामी", "1900", "प्रारंभिक उपन्यास", "हिंदी उपन्यास के प्रारंभिक काल का नारी चरित्र प्रधान और कौतूहलवर्धक उपन्यास।"],
  ["Lavang Lata (लवंग लता)", "किशोरी लाल गोस्वामी", "1899", "सामाजिक उपन्यास", "तत्कालीन कुलीन परिवारों के अंतर्विरोधों और प्रेम के आदर्शों को उजागर करने वाली कथा।"],
  ["Hridayaharini (हृदयहारिणी)", "किशोरी लाल गोस्वामी", "1890", "रोमांचक उपन्यास", "ऐतिहासिक पृष्ठभूमि पर रचित प्रेम, षड्यंत्र और विजय का भावपूर्ण औपन्यासिक चित्र।"],
  ["Indumati (इंदुमती)", "किशोरी लाल गोस्वामी", "1900", "प्रथम मौलिक कहानी", "शेक्सपियर के टेंपेस्ट से प्रेरित, हिंदी की प्रथम मौलिक कहानियों में गिनी जाने वाली अमर रचना।"],
  ["Sultana Razia Begum (सुल्ताना रज़िया बेगम)", "किशोरी लाल गोस्वामी", "1897", "ऐतिहासिक उपन्यास", "दिल्ली की प्रथम महिला सुल्तान रज़िया के शौर्य, दरबार के षड्यंत्रों और त्रासदी का इतिहास।"],
  ["Pariksha Guru (परीक्षा गुरु)", "लाला श्रीनिवास दास", "1882", "हिंदी का प्रथम उपन्यास", "लाला मदनमोहन की फिजूलखर्ची, कपटी मित्रों के जाल और ब्रजकिशोर की सच्ची मित्रता की सीख।"],
  ["Rani Ketki Ki Kahani (रानी केतकी की कहानी)", "इंशा अल्ला खाँ", "1803", "ठेठ हिंदी गद्य कथा", "यह वह कहानी है जिसमें न हिन्दवी छूट और न किसी बोली का पुट। कुंवर उदयभान और रानी केतकी का प्रेम।"],
  ["Nasiketopakhyan (नासिकेतोपाख्यान)", "सदल मिश्र", "1803", "खड़ी बोली गद्य कथा", "महर्षि उद्दालक के पुत्र नासिकेत का यमलोक गमन और सत्य, धर्म व सदाचार का उपदेश।"],
  ["Premsagar (प्रेमसागर)", "लल्लू लाल", "1805", "पौराणिक गद्य", "श्रीमद्भागवत के दशम स्कंध की कथा का खड़ी बोली हिंदी गद्य में रचित प्रारंभिक अनुपम ग्रंथ।"],
  // Classical Epics & Spiritual Literature (86-100)
  ["Ramcharitmanas - Balkand (रामचरितमानस - बालकाण्ड)", "गोस्वामी तुलसीदास", "1576", "महाकाव्य (Awadhi)", "वर्णानामर्थसंघानां रसानां छन्दसामपि। मंगलानां च कर्त्तारौ वन्दे वाणीविनायकौ॥ बंदउँ गुरु पद पदुम परागा। सुरुचि सुबास सरस अनुरागा॥ अमिअ मूरिमय चूरन चारू। समन सकल भव रुज परिवारू॥"],
  ["Ramcharitmanas - Ayodhyakand (रामचरितमानस - अयोध्याकाण्ड)", "गोस्वामी तुलसीदास", "1576", "महाकाव्य (Awadhi)", "जब तें रामु ब्याहि घर आए। नित नव मंगल मोद बधाए॥ भुवन चारिदस भूधर भारी। सुकृत मेघ बरषहिं सुख बारी॥ राम राज्याभिषेक का उल्लास और कैकेयी का कोपभवन।"],
  ["Ramcharitmanas - Aranyakand (रामचरितमानस - अरण्यकाण्ड)", "गोस्वामी तुलसीदास", "1576", "महाकाव्य (Awadhi)", "पंचवटी प्रवास, शूर्पणखा का मानमर्दन, मारीच प्रसंग, सीता हरण और शबरी पर कृपा कर प्रभु द्वारा नवधा भक्ति का दिव्य उपदेश।"],
  ["Ramcharitmanas - Kishkindhakand (रामचरितमानस - किष्किन्धाकाण्ड)", "गोस्वामी तुलसीदास", "1576", "महाकाव्य (Awadhi)", "ऋष्यमूक पर्वत पर सुग्रीव से मित्रता, बालि वध, वर्षा व शरद ऋतु का रूपक और जाम्बवंत द्वारा हनुमान जी को बल स्मरण।"],
  ["Ramcharitmanas - Sundarkand (रामचरितमानस - सुन्दरकाण्ड)", "गोस्वामी तुलसीदास", "1576", "महाकाव्य (Awadhi)", "शांतं शाश्वतमप्रमेयमनघं निर्वाणशांतिप्रदं। जामवंत के बचन सुहाए, सुनि हनुमंत हृदय अति भाए। लंका दहन और विभीषण शरणागति।"],
  ["Ramcharitmanas - Lankakand (रामचरितमानस - लंकाकाण्ड)", "गोस्वामी तुलसीदास", "1576", "महाकाव्य (Awadhi)", "सेतुबंध रामेश्वरम की स्थापना, अंगद रावण संवाद, कुंभकर्ण व मेघनाद वध और अधर्म के प्रतीक रावण का विनाश। धर्म की जय।"],
  ["Ramcharitmanas - Uttarkand (रामचरितमानस - उत्तरकाण्ड)", "गोस्वामी तुलसीदास", "1576", "महाकाव्य (Awadhi)", "दैहिक दैविक भौतिक तापा, राम राज नहिं काहुहि ब्यापा। काकभुशुण्डि-गरुड़ संवाद और कलियुग धर्म का विशद वर्णन।"],
  ["Vinaya Patrika (विनय पत्रिका)", "गोस्वामी तुलसीदास", "1585", "भक्ति गीति काव्य", "ऐसी मूढ़ता या मन की। परिहरि राम भगति सुरसरिता, याचक संभु-सवन की॥ तुलसीदास जी की प्रभु श्रीराम के दरबार में आर्त विनय।"],
  ["Kabir Bijak (कबीर बीजक)", "संत कबीरदास", "15th c.", "संत साहित्य", "मसि कागद छूयो नहीं, कलम गह्यो नहिं हाथ। साखी, सबद और रमैनी में निराकार ब्रह्म और अंतर्मुखी साधना का घोष।"],
  ["Kabir Sakhi Granth (कबीर साखी ग्रंथ)", "संत कबीरदास", "15th c.", "नीति दोहावली", "गुरु गोविंद दोऊ खड़े, काके लागूं पाँय। बलिहारी गुरु आपनो, गोविंद दियो बताय॥ पोथी पढ़ि पढ़ि जग मुआ, पंडित भया न कोय।"],
  ["Sur Sagar (सूरसागर)", "महाकवि सूरदास", "16th c.", "ब्रजभाषा भक्ति", "चरन कमल बंदौ हरि राई। जाकी कृपा पंगु गिरि लंघै, अंधे को सब कछु दरसाई॥ बहिरौ सुनै, मूक पुनि बोलै, रंक चले सिर छत्र धराई॥"],
  ["Padavali (मीरा पदावली)", "भक्त शिरोमणि मीराबाई", "16th c.", "भक्ति काव्य", "मेरे तो गिरधर गोपाल, दूसरो न कोई। जाके सिर मोर-मुकुट, मेरो पति सोई। पायो जी मैंने राम रतन धन पायो। वस्तु अमोलक दी मेरे सतगुरु, किरपा करि अपनायो।"],
  ["Bihari Satsai (बिहारी सतसई)", "महाकवि बिहारीलाल", "1662", "रीतिकाल दोहावली", "मेरी भव बाधा हरौ, राधा नागरि सोइ। जा तन की झाँई परैं, स्याम हरित दुति होइ॥ नहिं पराग नहिं मधुर मधु, नहिं विकासु इहिं काल। अली कली ही सौं बँध्यौ, आगे कौन हवाल॥"],
  ["Rahim Dohavali (रहीम दोहावली)", "अब्दुर्रहीम ख़ान-ए-ख़ाना", "16th c.", "नीति काव्य", "रहिमन धागा प्रेम का, मत तोरो चटकाय। टूटे पे फिर ना जुरे, जुरे गाँठ परी जाय॥ तरुवर फल नहिं खात है, सरवर पियहि न पान। कहि रहीम पर काज हित, संपति सचहि सुजान॥"],
  ["Panchatantra (पंचतंत्र - हिंदी अनुवाद)", "पंडित विष्णु शर्मा", "3rd c. BC", "नीतिकथा (Moral Fables)", "दक्षिण देश के महिला रोप्य नगर के राजा अमरशक्ति के मूर्ख राजकुमारों को छह मास में व्यवहार और नीति सिखाने वाली मित्रभेद, मित्रलाभ, काकोलूकीयम, लब्धप्रणाश और अपरीक्षितकारक की कालजयी कथाएँ।"]
];

const slugify = (text) => text.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');

const englishBooks = englishTitles.map((item, idx) => {
  const [title, author, year, category, sample] = item;
  const id = `en-${slugify(title)}-${idx + 1}`;
  return {
    id,
    title,
    author,
    year,
    language: 'english',
    category,
    difficulty: idx % 3 === 0 ? 'Easy' : idx % 3 === 1 ? 'Medium' : 'Hard',
    estimatedWords: 25000 + (idx * 2800),
    summary: `Classic public-domain masterpiece by ${author} (${year}).`,
    chapters: ['Chapter 1: The Opening', 'Chapter 2: The Departure', 'Chapter 3: The Rising Tide', 'Chapter 4: The Climax'],
    initialSampleText: sample.normalize('NFC')
  };
});

const hindiBooks = hindiTitles.map((item, idx) => {
  const [title, author, year, category, sample] = item;
  const id = `hi-book-${idx + 1}`;
  return {
    id,
    title,
    author,
    year,
    language: 'hindi',
    category,
    difficulty: idx % 3 === 0 ? 'Easy' : idx % 3 === 1 ? 'Medium' : 'Hard',
    estimatedWords: 15000 + (idx * 1900),
    summary: `${author} की अमर कालजयी साहित्यिक कृति (${year})।`,
    chapters: ['अध्याय 1: प्रारंभ', 'अध्याय 2: संघर्ष का विस्तार', 'अध्याय 3: चरमोत्कर्ष', 'अध्याय 4: उपसंहार'],
    initialSampleText: sample.normalize('NFC')
  };
});

const allBooks = [...englishBooks, ...hindiBooks];

const content = `// TypeSetu 200 Copyright-Free Classic Books & Public Domain Literature Catalog
// 100 Globally Public-Domain English Classics (Project Gutenberg / Standard Ebooks)
// 100 Public-Domain Hindi Literary Treasures (Premchand, Prasad, Bharatendu, Khatri, Tulsidas, Kabir)

export const BOOKS_CATALOG = ${JSON.stringify(allBooks, null, 2)};

export function getBooks(language = 'all', category = 'all', searchQuery = '') {
  return BOOKS_CATALOG.filter((book) => {
    const matchesLang = language === 'all' || book.language === language;
    const matchesCat = category === 'all' || book.category.toLowerCase().includes(category.toLowerCase());
    const matchesSearch =
      !searchQuery ||
      book.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
      book.author.toLowerCase().includes(searchQuery.toLowerCase()) ||
      book.category.toLowerCase().includes(searchQuery.toLowerCase()) ||
      book.summary.toLowerCase().includes(searchQuery.toLowerCase());

    return matchesLang && matchesCat && matchesSearch;
  });
}

export function getBookById(id) {
  return BOOKS_CATALOG.find((b) => b.id === id) || BOOKS_CATALOG[0];
}
`;

fs.writeFileSync(path.join(__dirname, '..', 'src', 'data', 'booksCatalog.js'), content, 'utf8');
console.log('Successfully generated 200 books:', allBooks.length, 'English:', englishBooks.length, 'Hindi:', hindiBooks.length);
